# Generated by Django 2.2.4 on 2021-03-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20210326_1926'),
        ('property', '0004_auto_20210326_1121'),
    ]

    operations = [
    ]
