# Generated by Django 2.2.4 on 2021-03-26 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_merge_20210326_1927'),
    ]

    operations = [
    ]
