# Generated by Django 2.2.4 on 2021-03-26 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0008_merge_20210326_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_text', models.TextField(verbose_name='Текст жалобы')),
                ('flat_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flat_number', to=settings.AUTH_USER_MODEL, verbose_name='Номер квартиры, на которую пожаловались')),
                ('who_complained', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_complained', to=settings.AUTH_USER_MODEL, verbose_name='Кто жаловался')),
            ],
        ),
    ]
