# Generated by Django 2.2.4 on 2021-03-26 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0009_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='who_liked',
            field=models.ManyToManyField(blank=True, related_name='who_liked', to=settings.AUTH_USER_MODEL, verbose_name='Кто лайкнул'),
        ),
    ]
