# Generated by Django 2.2.4 on 2021-03-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20210326_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.ManyToManyField(related_name='full_name', to='property.Flat', verbose_name='ФИО владельца')),
                ('owned', models.ManyToManyField(related_name='owned', to='property.Flat', verbose_name='Квартиры в собственности')),
                ('owner_pure_phone', models.ManyToManyField(related_name='pure_phone', to='property.Flat', verbose_name='Нормализованный номер')),
                ('owners_phonenumber', models.ManyToManyField(related_name='phonenumber', to='property.Flat', verbose_name='Номер владельца')),
            ],
        ),
    ]
