# Generated by Django 2.2.4 on 2021-03-27 14:44

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='full_name',
        ),
        migrations.AddField(
            model_name='owner',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='ФИО владельца'),
        ),
        migrations.RemoveField(
            model_name='owner',
            name='owner_pure_phone',
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Нормализованный номер владельца'),
        ),
        migrations.RemoveField(
            model_name='owner',
            name='owners_phonenumber',
        ),
        migrations.AddField(
            model_name='owner',
            name='owners_phonenumber',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер владельца'),
        ),
    ]
