# Generated by Django 2.2.4 on 2021-03-30 15:44

from django.db import migrations


def owned_for_owners(apps, schema_editor):
    Owner = apps.get_model("property", "Owner")
    Flat = apps.get_model("property", "Flat")
    for flat in Flat.objects.all():
        owner = Owner.objects.get_or_create(    
            full_name = flat.owner,
            owners_phonenumber = flat.owners_phonenumber,
            owner_pure_phone = flat.owner_pure_phone
        )[0]
        owner.owned.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20210328_1523'),
    ]

    operations = [
        migrations.RunPython(owned_for_owners)
    ]
